# Setup-MqttBroker.ps1?먯꽌 ?앹꽦?⑸땲?? Broker PC??Tailscale 二쇱냼?먮쭔 ?곌껐?⑸땲??
listener 1883 100.116.221.78
listener_allow_anonymous true

persistence true
persistence_location D:/Project1/mqtt/data/
autosave_interval 60

connection_messages true
log_timestamp true
log_type error
log_type warning
log_type notice
log_type information
